version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  users:
    container_name: users
    #build:
      #context: ./
      #dockerfile: ./users/Dockerfile
    image: maximilianop23/users:latest
    ports:
      - "8001:8001"
    #env_file: ./users/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: sasa
      COURSES_URL: courses:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  courses:
    container_name: courses
    #build:
      #context: ./
      #dockerfile: ./courses/Dockerfile
    image: maximilianop23/courses:latest
    ports:
      - "8002:8002"
    #env_file:
    #  - ./courses/.env
    environment:
      PORT: 8002
      DB_HOST: postgres14:5432
      DB_DATABASE: courses
      DB_USERNAME: postgres
      DB_PASSWORD: sasa
      USERS_URL: users:8001
    networks:
      - spring
    depends_on:
      - postgres14
      - users
    restart: always
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgress

networks:
  spring:
    name: spring